/// Unilorin Food Pricing Data  ///

// const ilorin_food_pricing = {
    // 'Unilorin PS', 
    // 'School Gas', 
    // 'Stella Maris', 
    // 'Oke Odo', 
    // 'Oko Oba', 
    // 'Tanke Ajanaku', 
    // 'Big Boy',
    // 'Sanrab', 
    // 'Mark', 
    // 'NNPC',
    // 'Tipper Garage ', 
    // 'Pipeline', 
    // 'F Division ', 
    // 'Tanke Junction ', 
    // 'Fate',
    // 'Basin', 
    // 'onCampus', 
    // "Adeta",
    // "Adewale Estate", 
    // "Mandate", 
    // "Cottage", 
    // "Gerin Alimi",
    // 'inside School',
    // 'Gaa Akanbi',
    // 'Olorunsoga',
    // 'Post Office',
    // 'Challenge',
    // 'Maraba',
    // 'Tawio',
    // 'General',
    // 'Oko Erin',
    // 'Surulere',
    // 'Al-hikmat',
    // 'Asa Dam',
    // 'Kwasu',
    // 'Agric',
    // 'Zango',
    // 'Kulende',
    // 'Oke Oyi',
    // 'Oyun',
// };


const tanke = {
    'Unilorin PS': 100, 
    'School Gas': 100, 
    'Stella Maris': 100, 
    'Oke Odo': 100, 
    'Oko Oba': 100, 
    'Tanke Ajanaku': 100, 
    'Big Boy': 100,
    'Sanrab': 100, 
    'Mark': 100, 
    'NNPC': 100,
    'Tipper Garage': 100, 
    'Pipeline': 150, 
    'F Division': 100, 
    'Tanke Junction': 120, 
    'Fate': 150,
    'Basin': 150, 
    'onCampus': 100, 
    "Adeta": 200,
    "Adewale Estate": 200, 
    "Mandate": 250, 
    "Cottage": 250, 
    "Gerin Alimi": 250,
    'Gaa Akanbi': 150,
    'Olorunsoga': 250,
    'Post Office': 200,
    'Challenge': 200,
    'Maraba': 200,
    'Tawio': 150,
    'General': 150,
    'Oko Erin': 150,
    'Surulere': 150,
    'Al-hikmat': 200,
    'Asa Dam': 200,
    'Kwasu': 300,
    'Agric': 200,
    'Zango': 200,
    'Kulende': 250,
    'Oke Oyi': 300,
    'Oyun': 300,
};

const taiwo = {
    'Unilorin PS': 200, 
    'School Gas': 150, 
    'Stella Maris': 150, 
    'Oke Odo': 150, 
    'Oko Oba': 150, 
    'Tanke Ajanaku': 150, 
    'Big Boy': 150,
    'Sanrab': 150, 
    'Mark': 150, 
    'NNPC': 150,
    'Tipper Garage': 150, 
    'Pipeline': 200, 
    'F Division': 150, 
    'Tanke Junction': 150, 
    'Fate': 200,
    'Basin': 200, 
    'onCampus': 200, 
    "Adeta": 100,
    "Adewale Estate": 150, 
    "Mandate": 200, 
    "Cottage": 200, 
    "Gerin Alimi": 150,
    'Gaa Akanbi': 200,
    'Olorunsoga': 200,
    'Post Office': 150,
    'Challenge': 150,
    'Maraba': 150,
    'Tawio': 100,
    'General': 100,
    'Oko Erin': 100,
    'Surulere': 100,
    'Al-hikmat': 150,
    'Asa Dam': 150,
    'Kwasu': 300,
    'Agric': 150,
    'Zango': 150,
    'Kulende': 200,
    'Oke Oyi': 300,
    'Oyun': 300,
};


exports.tanke = tanke;
exports.taiwo = taiwo;
